telegram:
  bot:
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}
    notify:
      delay:
        value: 10
        unit: MINUTES

app:
  crypto:
    check-price-delay-ms: 120000

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventify_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true